dist: xenial
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '10'
before_script:
  - git fetch --unshallow origin refs/heads/master:refs/remotes/origin/master
  - npm prune
  - npm update
script:
  - npm run lint
  - npm run test
  - npm run locale-tests
  - npm run build-package
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
