sudo: true
dist: trusty
language: node_js
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g npm@^3.8.0
  - export CHROME_BIN=/usr/bin/google-chrome
before_script:
  - "npm prune"
  - "npm update"
  - "export DISPLAY=:99.0"
  - "export TZ='Europe/Sofia'"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3" # give xvfb some time to start
script:
  - npm run lint
  - npm run test
  - npm run build-package
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
