name: Branch push

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - name: Checkout branch
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: |
        npm install
    - name: Lint
      run: npm run lint
    - name: Build
      run: |
        npm run build-package
    - name: Test
      run: |
        npm run test
        npm run locale-tests
    - name: Release
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
      env:
        TRAVIS: true
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        git reset --hard HEAD
        git checkout "${GITHUB_REF:11}"
        GITHUB_ACTION=true npm run semantic-release
